SALTEDGE_API_ENDPOINT = "https://www.saltedge.com/api"

CREATE_SALTEDGE_CUSTOMER_ACCOUNT_URI = "/v5/customers"
CREATE_SALTEDGE_CUSTOMER_ACCOUNT_URL = SALTEDGE_API_ENDPOINT + CREATE_SALTEDGE_CUSTOMER_ACCOUNT_URI

CREATE_SALTEDGE_USER_CONNECTION_URI = "/v5/connect_sessions/create"
CREATE_SALTEDGE_USER_CONNECTION_URL = SALTEDGE_API_ENDPOINT + CREATE_SALTEDGE_USER_CONNECTION_URI

COUNTRIES_INFO_URI = "/v5/countries"
COUNTRIES_INFO_URL = SALTEDGE_API_ENDPOINT + COUNTRIES_INFO_URI

ACCOUNT_INFO_URI = "/v5/accounts"
ACCOUNT_INFO_URL = SALTEDGE_API_ENDPOINT + ACCOUNT_INFO_URI

GET_CONNECTIONS_INFO_URI = "/v5/connections"
GET_CONNECTIONS_INFO_URL = SALTEDGE_API_ENDPOINT + GET_CONNECTIONS_INFO_URI
