# Generated by Django 3.0.6 on 2020-05-20 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0002_auto_20200520_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='se_customer_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='bank_customer_info',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_backend.BankCustomerInfo'),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='bank_provider',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_backend.BankProvider'),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='country_code',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='provider_name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='se_categorization',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='se_connection_secret',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='se_customer_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='se_last_success_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='se_next_refresh_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='se_provider_code',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='se_provider_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='se_status',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
