# Generated by Django 3.0.6 on 2020-05-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0002_auto_20200519_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='se_customer_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='se_customer_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='se_identifier',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
