# Generated by Django 3.0.6 on 2020-05-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0003_auto_20200520_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_flag_icon_url',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='se_country_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='UserConnection',
        ),
    ]
