# Generated by Django 3.0.6 on 2020-05-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0003_auto_20200519_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='country_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_backend.Country'),
        ),
    ]
