# Generated by Django 3.0.6 on 2020-05-21 12:08

import app_backend.models.user_connection
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0004_auto_20200521_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('se_customer_id', models.BigIntegerField()),
                ('se_identifier', models.CharField(max_length=100)),
                ('provider_name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('se_provider_code', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('se_status', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('se_next_refresh_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('se_last_success_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('se_provider_id', models.IntegerField(blank=True, default=None, null=True)),
                ('se_connection_secret', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('se_categorization', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('country_code', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('se_conn_session_status', models.CharField(default=app_backend.models.user_connection.SaltEdgeConnectSessionStatus['DEFAULT'], max_length=10)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.AppUser')),
                ('bank_customer_info', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_backend.BankCustomerInfo')),
                ('bank_provider', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_backend.BankProvider')),
            ],
        ),
    ]
