# Generated by Django 3.0.6 on 2020-05-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0004_auto_20200519_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconnection',
            old_name='se_secret',
            new_name='se_connection_secret',
        ),
        migrations.AddField(
            model_name='appuser',
            name='se_customer_secret',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
