# Generated by Django 3.0.6 on 2020-05-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0005_auto_20200520_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='country_id',
            new_name='country',
        ),
    ]
