# Generated by Django 3.0.6 on 2020-05-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0006_auto_20200521_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
