# Generated by Django 3.0.6 on 2020-05-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0006_auto_20200520_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='bank_customer_info_id',
            new_name='bank_customer_info',
        ),
        migrations.RenameField(
            model_name='bankcustomerinfo',
            old_name='bank_provider_id',
            new_name='bank_provider',
        ),
        migrations.RenameField(
            model_name='bankprovider',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='userconnection',
            old_name='bank_provider_id',
            new_name='bank_provider',
        ),
        migrations.RenameField(
            model_name='userconnection',
            old_name='user_id',
            new_name='user',
        ),
    ]
