# Generated by Django 3.0.6 on 2020-05-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0007_auto_20200521_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='se_customer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
