# Generated by Django 3.0.6 on 2020-05-21 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0010_auto_20200521_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankprovider',
            old_name='provider_name',
            new_name='se_provider_name',
        ),
        migrations.RemoveField(
            model_name='bankprovider',
            name='bank_country',
        ),
        migrations.RemoveField(
            model_name='bankprovider',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='bankprovider',
            name='se_country_code',
        ),
        migrations.RemoveField(
            model_name='userconnection',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='userconnection',
            name='se_identifier',
        ),
        migrations.RemoveField(
            model_name='userconnection',
            name='se_provider_code',
        ),
        migrations.RemoveField(
            model_name='userconnection',
            name='se_provider_id',
        ),
        migrations.AddField(
            model_name='account',
            name='se_bank_account_id',
            field=models.CharField(default='Not Set', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='user_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_backend.UserConnection'),
        ),
        migrations.AddField(
            model_name='bankprovider',
            name='se_provider_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userconnection',
            name='se_connection_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='se_conn_session_status',
            field=models.CharField(default='UNINITIATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='se_customer_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
