# Generated by Django 3.0.6 on 2020-05-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0013_auto_20200522_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='se_account_id',
            field=models.CharField(max_length=100),
        ),
    ]
