# Generated by Django 3.0.6 on 2020-05-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0014_auto_20200522_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='se_available_money',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
