# Generated by Django 3.0.6 on 2020-05-22 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0015_auto_20200522_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bank_customer_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_backend.BankCustomerInfo'),
        ),
    ]
