# Generated by Django 3.0.6 on 2020-06-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0018_auto_20200525_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='se_bank_account_id',
            field=models.CharField(default='Not Set', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='se_transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='se_connection_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, unique=True),
        ),
    ]
