# Generated by Django 3.0.6 on 2020-06-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0021_auto_20200617_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='full_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='google_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='photo_url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
