# Generated by Django 3.0.6 on 2020-06-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0022_auto_20200617_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='sign_in_method',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
