# Generated by Django 3.0.6 on 2020-06-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0023_appuser_sign_in_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='photo_url',
            new_name='profile_photo',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='country',
            new_name='resident_country',
        ),
        migrations.AddField(
            model_name='appuser',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
