# Generated by Django 3.0.8 on 2020-07-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0025_auto_20200713_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='currency',
            new_name='currency_code',
        ),
        migrations.AddField(
            model_name='country',
            name='currency_name',
            field=models.CharField(default='NA', max_length=10),
            preserve_default=False,
        ),
    ]
