# Generated by Django 3.0.6 on 2020-07-13 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0026_auto_20200713_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='country_of_origin',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_of_origin', to='app_backend.Country'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='resident_country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident_country', to='app_backend.Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_flag_icon_url',
            field=models.CharField(blank=True, default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency_name',
            field=models.CharField(max_length=100),
        ),
    ]
