# Generated by Django 3.0.6 on 2020-07-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0027_auto_20200713_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='se_bank_account_id',
            field=models.CharField(default='Not Set', max_length=100),
        ),
    ]
