# Generated by Django 3.0.6 on 2020-07-13 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0028_auto_20200713_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='app_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_backend.AppUser'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('app_user', 'se_bank_account_id')},
        ),
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
    ]
