# Generated by Django 3.0.6 on 2020-07-13 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0029_auto_20200713_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_backend.Country'),
        ),
    ]
