# Generated by Django 3.0.6 on 2020-07-13 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0030_account_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconnection',
            name='country_code',
        ),
        migrations.AddField(
            model_name='userconnection',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_backend.Country'),
        ),
    ]
