# Generated by Django 3.0.8 on 2020-07-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0031_auto_20200713_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankprovider',
            name='icon_url',
            field=models.CharField(blank=True, default=None, max_length=2048, null=True),
        ),
    ]
