# Generated by Django 3.0.6 on 2020-07-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0031_auto_20200713_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnection',
            name='se_connection_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
