# Generated by Django 3.0.6 on 2020-07-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0032_bankprovider_icon_url'),
        ('app_backend', '0032_auto_20200714_0938'),
    ]

    operations = [
    ]
