# Generated by Django 3.0.6 on 2020-07-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0033_merge_20200714_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='available_credit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='account',
            name='card_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='card_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='closing_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='account',
            name='deposit_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='deposit_open_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='deposit_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='interest_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='account',
            name='se_available_money',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='se_balance',
            field=models.FloatField(),
        ),
    ]
